# Microbes to Watch {#sec-microbes}


Your gut as seen by consumer-priced sequencing technology contains many more unique microbial species than you can possibly track, at least hundreds in most people and potentially over 1000. I've seen 1083 different ones in my own results. And that's just using the comparatively crude 16S technology. More comprehensive estimates based on other technology find as many as 36,000 different species^[See [@frank_molecular-phylogenetic_2007] or click for the [open access download](http://www.pnas.org/content/104/34/13780.full)]!  With that much variety, how do we find the ones that matter?

Fortunately, only about 14 strains of 10 species account for 80% of a typical gut microbiome^[See the detailed estimates here: [@kraal_prevalence_2014]]

In this chapter, we'll just consider the most common microbes and the overall consensus on what they do.  Later, in the chapter on [experiments](#sec-experiments), we'll show more about how you can _manipulate_ them.

What you're really wondering is how does your sample compare to others? Do you have an unusual abundance (or lack) of a particular taxa? Is there something that might indicate a greater or lesser similarity between your sample and certain other types of people? That is a very difficult question which we'll address over and over in this book, but for now let's just look at overall abundances of some key microbes. 

## Phylum {#microbesPhylum}

::: {.callout-important}
This section is under construction
:::

In biology, a phylum (/ˈfaɪləm/; plural: phyla) is a taxonomic rank used to classify organisms. It is a group of related classes. The term was coined by Ernst Haeckel in 1866.

Traditionally, in botany the term division has been used instead of phylum, although the International Code of Nomenclature for algae, fungi, and plants accepts the terms as equivalent. Depending on definitions, the animal kingdom Animalia contains about 31 phyla, the plant kingdom Plantae contains about 14 phyla, and the fungus kingdom Fungi contains about 8 phyla.

At its most basic, a phylum can be defined in two ways: as a group of organisms with a certain degree of morphological or developmental similarity (the phenetic definition), or as a group of organisms with a certain degree of evolutionary relatedness (the phylogenetic definition). Attempting to define a level of the Linnean hierarchy without referring to (evolutionary) relatedness is unsatisfactory, but a phenetic definition is useful when addressing questions of a morphological nature—such as how successful different body plans were.

The concept of phylum is based on the idea that organisms that share a common ancestor are more closely related to each other than organisms that do not share a common ancestor. This means that organisms in the same phylum are more likely to have similar characteristics than organisms in different phyla.

For example, all the animals in the phylum Chordata share a common ancestor that had a notochord, a rod-shaped structure that supports the body. This means that all chordates have a notochord at some point in their development.

The concept of phylum is also based on the idea that organisms in the same phylum are more likely to have a similar evolutionary history than organisms in different phyla. This means that organisms in the same phylum are more likely to have evolved from a common ancestor in a similar way.

For example, all the animals in the phylum Chordata have a common ancestor that lived about 500 million years ago. This ancestor was a small, worm-like creature that lived in the ocean. Over time, this ancestor evolved into the different types of animals that we see today, including humans, fish, and birds.

The concept of phylum is a useful tool for classifying organisms and understanding their evolutionary relationships. It is also a useful tool for studying the diversity of life on Earth.

The gut microbiome of most westerners is dominated by _Firmicutes_ and _Bacteroidetes_, which together make up 80% or more of the total sample.  Most people also have smaller amounts of _Actinobacteria_,  _Proteobacteria_ and _Verrucomicrobia_. This overall composition is so common in healthy people that it's tempting to assume their dominance is "natural" or "normal", but like much else with the microbiome, the situation is different outside the western world, a clue that it's difficult to summarize a single individual's microbiome as "good" or "bad." It all depends.



## Genus {#microbesGenus}

::: {.callout-important}
This section is under construction
:::

In biology, a genus is a taxonomic rank used to classify organisms. It is a group of species that are closely related to each other. The genus name is always capitalized and comes first in the binomial nomenclature of a species. For example, the genus name for humans is Homo, and the species name is sapiens.

The concept of genus was first introduced by the Swedish naturalist Carl Linnaeus in his 1753 work Species Plantarum. Linnaeus divided all living things into three kingdoms: plants, animals, and minerals. He then divided each kingdom into classes, orders, genera, and species.

The genus is a useful tool for classifying organisms because it allows us to group together species that share similar characteristics. For example, all the species in the genus Homo share the following characteristics: they are bipedal, they have large brains, and they use tools.

The genus is also a useful tool for understanding the evolutionary relationships between organisms. Species that are closely related to each other are usually placed in the same genus. For example, humans and chimpanzees are both placed in the genus Homo. This suggests that humans and chimpanzees are closely related, and that they share a common ancestor.

The genus is an important part of the biological classification system. It is a useful tool for grouping together organisms that share similar characteristics, and for understanding the evolutionary relationships between organisms.

In the context of the human microbiome, the genus is a useful way to group together different types of bacteria. For example, the genus *Lactobacillus* contains many different species of bacteria that are found in the human gut. These bacteria play an important role in digestion and immune function.

The genus is also a useful way to study the evolution of the human microbiome. By comparing the genomes of different species of bacteria in the same genus, we can learn about how these bacteria have evolved over time. This information can help us to understand how the human microbiome has changed in response to changes in our environment.

The term "genus" may not make intuitive sense to somebody used to thinking of eukaryotes or other organisms that reproduce via gametes. This is because the concept of genus is based on the idea of shared characteristics, which is not always clear-cut in the case of prokaryotes.

For example, the genus *Escherichia* contains many different species of bacteria that are very different from each other in terms of their appearance and their metabolism. However, they all share a common ancestor and they all have a similar DNA sequence. This is why they are all placed in the same genus.

Another example is the genus *Lactobacillus*. This genus contains many different species of bacteria that are found in the human gut. They all have a similar appearance and they all ferment carbohydrates. However, they have different DNA sequences and they are not all closely related to each other. This is why some scientists believe that the genus Lactobacillus should be divided into several different genera.

The concept of genus is also complicated by the fact that prokaryotes can reproduce asexually. This means that they do not produce gametes, and they do not have a sexual cycle. As a result, it can be difficult to determine how closely related two species of prokaryotes are.

Despite these challenges, the concept of genus is still useful for classifying prokaryotes. It allows us to group together organisms that share similar characteristics, and it can help us to understand the evolutionary relationships between organisms.

You're likely to hear most about the genus level because it's the most detail that cheap sequencing technologies can get right -- most of the time. 


_Bifidobacterium_ is a key component of virtually all popular probiotic supplements, partly because it is so easy to manufacture, but also due to its proven association with sleep and other aspects of health. A six month picture of my levels shows some dramatic ups and downs (See [Hacking Sleep](#sec-experimentSleep).


## Species

::: {.callout-important}
This section is under construction
:::

When you hear the term "species", you probably think of a specific kind of creature, like a dog or a cat. More generally, among the kinds of plants and animals we encounter in the visible world, the term "species" refers broadly to organisms that can mate with one another to produce offspring of the same kind. Cats and dogs are different species because they can't mate with each other.

But bacteria don't mate: they reproduce by dividing themselves in half. So how do we define a species? In fact, even terms like "parent" or "child" aren't quite appropriate if each new cell is an identical copy of the old one. For very broad categories, like phylum or even genus, the similarities among like cells is high enough that we feel comfortable grouping them together with a common name, but at what point do we reach the lowest, most _specific_ level. 

The answer is tricky for another reason, called _horizontal gene transfer_, a process by which sometimes (in fact, quite often), a microbe will absorb genes from nearby organisms, altering its genome and its corresponding functions, sometimes significantly. Once that happens, the resulting new microbe can itself divide indefinitely, producing more and more copies of itself with the new gene. Although the new microbes still mostly resemble their original ancestor, if the new gene makes a protein that affects your body somehow, it might as well be an entirely different species.

The term "species" may not make intuitive sense to somebody used to thinking of eukaryotes or other organisms that reproduce sexually. This is because the concept of species is based on the idea of interbreeding, which is not always possible in the case of prokaryotes.

For example, the bacterium Escherichia coli can reproduce both sexually and asexually. When E. coli reproduces sexually, it produces two new cells that are genetically identical to each other. However, when E. coli reproduces asexually, it produces new cells that are not genetically identical to each other. This means that it is possible for two strains of E. coli to be genetically very different from each other, even though they are both members of the same species.

Another example is the bacterium Lactobacillus. This bacterium can also reproduce both sexually and asexually. However, Lactobacillus does not produce gametes, and it does not have a sexual cycle. As a result, it is not possible to determine how closely related two strains of Lactobacillus are based on their DNA sequence.

The concept of species is also complicated by the fact that prokaryotes can evolve very rapidly. This is because prokaryotes have a very simple genome, and they can replicate their DNA very quickly. As a result, it is possible for two strains of prokaryotes to evolve into two different species in a very short period of time.

Despite these challenges, the concept of species is still useful for classifying prokaryotes. It allows us to group together organisms that share similar characteristics, and it can help us to understand the evolutionary relationships between organisms.

Another way that "species" is different from our everyday usage of the term relates to the way microbial organisms are further differentiated by "strain".

A strain is a group of organisms within a species that share certain characteristics. Strains can be defined based on their physical appearance, their genetic makeup, or their response to certain environmental conditions. Strains are often used in microbiology to study the diversity of a particular species.

For example, there are many different strains of E. coli. Some strains of E. coli are harmless, while others can cause food poisoning. The strains of E. coli that cause food poisoning are typically more resistant to antibiotics than the harmless strains.

Strains can also be used to study the evolution of a particular species. By comparing the genomes of different strains of a species, scientists can learn about how the species has evolved over time. This information can help scientists to understand how the species is likely to respond to changes in the environment.

In other words, a strain is a group of organisms within a species that share certain characteristics. Strains can be defined based on their physical appearance, their genetic makeup, or their response to certain environmental conditions. Strains are often used in microbiology to study the diversity of a particular species, and to study the evolution of a particular species.



