# Microbes and You {#sec-scienceMicrobesYou}

## The promise and disappointment of genetic testing
If you want to optimize your health, you’ll eventually need to understand more about your genes. Wearable devices like FitBit or Apple Watch, or a nutrition or dieting app like MyFitnessPal, can help optimize some aspects of your physical body but hard work and discipline will take you only so far. As you reach the limits of how much you can change, you’ll settle into the discovery that the genetic component is undeniable.  Over one million customers of the genetic testing company 23andme have opted to look at their genes in part to understand better what their own limits are.

Genes do seem important. Everything from twin studies to laboratory experiments with knock-out mice shows that large parts — perhaps the major part — of our health and even behaviors are determined as much by our genetic makeup as by the environment in which we put ourselves.

Still, despite much progress since the unveiling of the Human Genome Project in 2001, there are frustratingly few examples of genes that decisively determine one trait or another. Except for a few simple cases like eye or hair color, most genes seem merely to increase or decrease the odds one way or another. When you read the details about your own genes, you’ll be disappointed at how little about genetic testing is truly insightful.  Did you really need a DNA test to tell you that you are lactose intolerant? 

Worse, even when the science tells you something you didn’t know — your likelihood of Alzheimers or Grave’s disease — there often isn’t much you can do about it besides eat healthy and get plenty of exercise. In fact, with disappointingly few exceptions, nearly all conclusions you’ll get with DNA results will be advice you should be doing anyway.

What’s an optimizer to do? On the one hand, the evidence is powerful that genes determine much or most of your health, but on the other hand, you can’t do much about it beyond the obvious. The results of human DNA testing just aren’t all that actionable.

Fortunately, one of the most exciting consequences of the latest science on human genetics is the role played by other genes in your body. And the best news: you can change them! And you don’t need a fancy laboratory with complicated equipment for recombinant DNA. This book will show you how, through experiments on the types of food you eat and deliberate changes you can make in your environment, you can make a significant difference in kinds and functions of the genes inside you.

## Most of your DNA is not fixed
If you could zap me with a scanner that can break down everything in my body, all the physical “hardware” inside me right now, you’d find a curious fact: although it’s true that 99% of the weight and size of what you see is human (blood, skin, bones, organs, etc.), only about half of the _cells_ are human, and even less than that  — perhaps as little as 1%  — of the DNA-carrying genes are human.


What’s the rest? Who am I, if only 1% of the genes inside me are human? The answer is microbes, and as befits something that so outnumbers the “human” part of us, they play a large role in everything about what we do, from our health to our moods and even to our motivations.  To put this more precisely, humans have 20,000 - 25,000 genes, but just the microbes in your intestines alone have an estimated [2 to 4 million genes](http://science.sciencemag.org/content/292/5519/1115?ijkey=fb8a4e2eba0ee558d13e99b9d9ca1c442b2f1473&keytype2=tf_ipsecsha).


These microbes and the important DNA they carry are constantly changing, sometimes quite significantly, depending on what you eat, who you’re with, and a host of other factors that you can manipulate. 

## Microbes are older than any of us
We tend to think of the invisible, single-celled microbes as "primitive", not nearly as "advanced" as we humans, with our marvelous brains and ability to transform the earth with airplanes and skyscrapers and nuclear reactors and all the rest. But that's what we would think, wouldn't we? In fact, the microbes are everywhere, literally everywhere on earth, in the sky, even deep underground. We can't go anywhere without encountering microbes because, well, there are even microbes on and inside us. Humans can't survive without microbes. So what does it even mean to say we're "better" or more "advanced" than they are?

Before the microscope, people didn't even know that microbes existed. Similarly, until the advent of large-scale gene sequencing machines in the past ten years, almost nothing was known about the amazing ubiquity and resilience of microbes.
Yes, they’re single-celled and yes many of their cellular functions seem more straightforward than the functions of a multi-cellular creature like us, but it would be a mistake to assume that means microbes -- collectively -- are less influential, and certainly it would be a big error to assume they are less important. Fact is, these organisms have been around, breathing, eating, multiplying, for billions of years, often in pretty much the same form that they are today. These things have survived every imaginable planetary condition from volcanoes to the depths of the ocean to the inside of nuclear reactors. Global Warming means nothing to these guys, who have seen and thrived all over the earth since the day life first appeared.

## What they want
Because they have such a huge advantage over us, in lifespan (each microbe is an exact divided copy of itself, going back a zillion generations), in speed of replication (they can double in just a few minutes under the right conditions),  and ubiquity (as I said, cellwise they far outnumber us), they can afford to colonize every new imaginable environment. 

And that's what they do, every time a new frontier opens to them. The moment of your birth, for example, when you left the (mostly) sterile conditions of your mother's womb, they immediately flooded all over your skin, mostly coming from your mother, and in that fresh environment they used their first-mover advantage to get a stronghold that in many cases lasts your entire life. Many (most?) of the microbes that matter arrived inside you this way, originally, and many of them are still there today, decades, even half a century or more later. 

To survive, they need one thing: something to eat. Being so tiny, they don't need much, and they mostly eat things that you (and other larger creatures) weren't interested in anyway. (Or, since they were here first, it's probably more accurate to say that you and I must live on the foods that they don't want. A cheeseburger is only food for you because you snatch it faster than they do. Leave it outside for a while and they'll get it eventually).

## Who’s in charge?
Collectively, the multitude species of microbes will eat just about everything, but individually each species has its preferences. When they're outside the body, as I said, they can "colonize" new territories (like fresh baby skin) to get what they want, but those inside your tummy are at the mercy of whatever it is you decide to put into your mouth.

Often, that's not a big deal: many species thrive on the same proteins, carbohydrates, and fats that you do. But some species do better than others with certain types of foods, and this is where the line between your human desires and theirs becomes unclear.

Eighty percent of all your brain's outside receptors -- counting all the nerve endings everywhere on your skin -- eighty percent complete their connections in the gut. The main switching grounds, an area called the vagus nerve, does _something_.  What? We know very little, but we see some evidence that the purpose -- the reason that not 1% or 10% or 50% but a full 80% of all the receptors go to the gut -- is so the microbes can tell your brain what to do.

When you find yourself feeling hungry, ask yourself who is feeling hungry. Scientists have traced that feeling of hunger to changes in certain hormones like leptin, but wait -- why did the leptin levels change in the first place? Could it be that a microbe someplace was manipulating your leptin levels, perhaps by poking that vagus nerve just the right way -- to get your brain to start thinking about whatever food that microbe wants?

This isn't as ridiculous as it sounds, the idea that microbes could influence your feelings and desires. Think about a disease like the rabies. Because it spreads through saliva, it can't find new territory unless its host somehow finds itself exchanging saliva -- biting -- another potential host. So guess what a rabies victim can't stop thinking about? Biting a new victim.  The microbe literally puts a thought into the mind.

There are many other examples, so many in fact as to be potentially a bit disturbing when we realize that we humans may be much more at the mercy of tiny microbes than we think.  Links have been made between microbes and schizophrenia, stress, anxiety, self-grooming, and much more.  Autism Spectral Disorders, which have always seemed puzzling because of the relationship they seem to have with digestive problems, are also linked to microbes,  or the lack thereof.

Perhaps the most intriguing example is the common parasite _Toxoplasma gondii_, the strange organism that can only reproduce in the intestines of cats. A parasite seen often in all warm-blooded mammals, it's found in about a third of the global population of humans too.  It's one of the reasons they tell pregnant women to stay away from cat litter. But here's the interesting part: when a Toxo protozoa infects a mouse, it leaves cysts in the mouse brain that make it attracted to cat urine! Yes, it changes the neurology of a mouse so that it's more likely to end up inside a cat's tummy -- exactly where it can reproduce.

Think about this too much, and you'll end up with the obvious question: what other weird microbes are infecting us right now? Can we explain some of our own behaviors this way? Is there a human equivalent of these infections, driving us to do things we "ordinarily" wouldn't do? And maybe these microbes are so ubiquitous, teeming all over us and in our brains, maybe there's no way to even know what "ordinary" or "normal" human behavior is.

## What is health?
Modern, western medicine tends to think reductively about health, dividing the body into pieces like organs and cells and prescribing interventions that target one particular aspect of the whole, with specific drugs or supplements. But of course nothing as complex as the body and health can be simplified this much. Maybe you can't really think about human hardware without thinking about the whole ecology that goes with it, the various organisms live in and around us and greatly outnumber us.

From this perspective, the whole idea of "health" takes on a new meaning, because we're no longer talking about the status of a single organism -- me -- but rather about the entire functioning ecosystem of many, many living things, including  the "me" that I want to refer to as a human. You can't survive long without these microbes any more than you can survive without air. This whole "me", sometimes referred to as the "holobiont", is perhaps the true unit of what it means to be human and healthy. 

Redefining health in terms of the holobiont has important implications for treatment. If it's the _entire_ ecology in and around me, then targeting a single unit or a single symptom may not be the best solution. Treating a skin condition with an antimicrobial salve, for example, may inadvertently destroy other microbes necessary for some other function. Teeth-brushing or hair shampooing, while seemingly fundamental aspects of hygiene, may not be simply about "getting rid" of something that we think of as "bad", such as an unwanted odor. In your zeal to rid yourself of one thing (the odor) you may be introducing another (a skin condition someplace else). It might be better to treat the root cause, figure out why the odor is there in the first place.

But what is a "root" cause in a complex ecological system like our bodies? After all, anything that affects one part of the body is likely to affect others as well. Is there a way to affect everything all at once?

Diet is one way. What you eat is an input to the entire ecosystem.

Where you live -- your environment -- is another. From the air you breathe (is it clean? cold?) to the amount of stress you face, change your immediate surroundings and you will change the ecosystem.

If we no longer think of our bodies as independent parts, then our treatment options must be holistic. No intervention should be done without considering the consequences it has on the whole. Similarly, it may often (usually?) be true that the best treatments are dietary or environmental -- facing the entire holobiont at once.









