
# What is Personal Science? {#sec-personal_science}

Although the techniques of science are useful in all aspects of life, many people are attracted to Personal Science out of concern over a personal health issue.

Most of us grow up believing in *experts.* Whether it's a proclamation from the government, a highly-regarded book, a credentialed doctor, or an experienced family member, it only makes sense to rely on others who have spent more time with the situation than you have, or who have gained a reputation for reliably solving similar problems.

But what happens when experts disagree? Of course, you can simply choose to believe one or another based on some reasonable criteria, like their track record with treating problems like yours.

Unfortunately, many people find themselves suffering from a chronic condition for which expert advice seems to fail. One doctor says "do this" and another says the exact opposite. One treatment seems to work for while and then it no longer does. Sometimes the symptoms seem to disappear at random, despite undergoing no treatment at all. Five doctors give six different suggestions.

## How to Begin

If you suffer from a chronic condition, one of your first struggles is simply *how bad is it?* What is the precise version or name of this disease? What makes you different from a healthy person, or from the healthy person you used to be? Are there other people with the same condition, and if so, how does your situation compare to theirs? Are you getting better or worse?

In other words, you want to know the *context*. The first step in any treatment plan requires that you understand how you compare...to healthy people, to those who have the same condition as you do, to people who have partially or fully recovered. Are you improving or deteriorating?

Even symptom tracking is just one aspect of the question of context. I want to know more precisely the conditions under which my problem gets better or worse. In other words, what is the *context*? (e.g. are my migraines triggered by high altitudes, by caffeine, by stress, by something else? All of these are just other ways of saying "context").

One simple example: what's the best way to treat a headache? There's no good answer to that question unless you understand something about the context surrounding the person involved. The appropriate response will depend on whether he or she:

-   gets headaches all the time.
-   rarely gets headaches.
-   drank heavily the night before.
-   recently ate raw seafood from a street vendor.
-   Underwent a course of antibiotics for a tick bite last summer and seemed to get better until now.

We know intuitively that each medical situation depends on the circumstances. Doctors are helpful partly because they've seen so many other cases that they can quickly focus attention on the aspects that are important to a specific individual. In other words, doctors are trained to recognize the full *context*, to see how this situation compares to others.

## Reference Values

Much of our understanding of context is driven by reference values. A doctor knows whether your cholesterol is high or low based on large population studies of other people. Every health study is essentially just a way to calculate reference values: of the n people exposed to this treatment, some fraction will improve. If that fraction is large enough, we say the treatment works. If not, the treatment doesn't work.

So the real question in any medical condition is: what is the reference value? What is the standard by which I am judging my current condition?

For many (most) situations, the reference values have been pre-computed based the medical community's long experience treating patients like you. We know that X% of people with your type of cancer respond well to this drug. We know that Y% of people who smoke develop this disease. And on and on.

But for some situations -- like data from microbiome tests -- there is no reference value. Nobody knows what a "healthy" microbiome looks like. We need more data before we can say definitively that such-and-such abundance levels are "healthy" or "unhealthy".

In other cases, there are reference values for the general population, but not necessarily for you. The average height of a 3-year-old girl, for example, is based on data from umpteen thousands of 3-year-olds, but what about among 3-year-olds of your ethnic group, or your family, or people of your socio-economic class, or those in your neighborhood? Whether to consider *your* 3-year-old for special treatment depends entirely on which reference group you are using.

How can we get those reference values?

In other cases, a treatment may be too new, or too crazy, for there to be reference values. A terminal cancer patient who tries an experimental treatment, for example, is living in a world of unknown reference values. Importantly, after they try the treatment, they become one of the reference values. And that's great! we now have a reference value for that treatment --- but only if somebody bothers to record it. Often that data simply falls on the floor with nobody to catch it.

## Quantifying the anecdotal

If the results of a treatment are not recorded, we still have reference values. People still rely on word of mouth --- anecdotes --- when looking for new treatments. But those reference values are anecdotal. You regularly hear stories of the form "I tried X and it worked for me". Hear enough of those stories and you may want to try it yourself. But how many of those stories constitutes "enough" to try for yourself?

What if there were a common way for everyone who tries X to record their results quantitatively?

That's the idea behind symptom tracking, and it's a nice start. Some companies try to add fancy additional features on top, like using machine learning to try to guess better than you can alone about the various correlations found within your data. Many companies go this direction --- gather enough data, either from yourself or from others, so that we can predict the causes for various states. Again, that's interesting and it's a nice start, but it's limited.

What you really want --- and the key, original idea behind Personal Science --- is to let you take that quantitative data and *compare* it to others: others like you, people who you consider to be just like you except for such-and-such symptom.

Now, in some cases, a symptom tracking or quantified self product will let you see yourself compared to *an aggregated* summary of all other users. Fitbit might let you compare yourself to all those of your sex or age, for example, or maybe those in your geography. This is a good start.

But what if you could choose your own subset of users with whom you want to compare yourself? Because only *you* know which type of person you identify with, or to which type of health condition you want to belong, Personal Science lets you analyze and study the data as a whole.

That's why it's *personal* -- it's about the one, unique data point that is you -- and why it's *science* -- democratize the quantitative tools of science to let you understand your condition, for yourself.
