
# Intro {-}


>>Healthy people are all alike; every unhealthy person is unhealthy in their own way. \
-- Leo Tolstoy (sort of) _Anna Karenina_.

---

How healthy are you?

This simple question is surprisingly difficult to answer quantitatively. Maybe you _feel_ healthy, but is that enough? To really understand your health, you'll need some context: How do you feel compared to ... yesterday?  a few years ago? How about compared to your close friends or family, or to an athlete or health expert you admire? 

A quantitative answer requires a systematic approach that integrates data collection, experiments, hypotheses, and iteration -- tools that are familiar to any scientist. 

---

Science is curiosity, a genuine and humble search for truth using a never-ending process of systematic experimentation.  It's open to everyone and can be applied to any situation, including situations that affect you right now.  It's _Personal Science_ when you use the scientific method to discover important insights about the wellness and performance of yourself and those around you. 

This book will introduce you to one exciting area of personal science: understanding your own microbiome. Our [companion web site](https://personalscience.com/) lets you upload your own data and compare it to others to make your own discoveries.

*NOTE* You're reading an online e-book that will eventually be integrated into the main site. For now, treat it like an instruction manual.  _We want your feedback!_ so please email us at [info@personalscience.com](mailto:info@personalscience.com). To move to the next page, either hit the arrow buttons on your keyboard, or click the arrows at the very bottom of the page.  Enjoy!


# What is Personal Science? 


The term "personal science" was first popularized by the late Seth Roberts, an Emeritus Professor in the Psychology at University of California, Berkeley. His best-selling book^[[@roberts_shangri-diet]] and [popular blog](https://sethroberts.net/)^[His blog, active until his death in 2014, is actively discussed on a Facebook Community: https://sethroberts.net/2016/01/13/seth-roberts-community-on-facebook/ ] insisted that much of modern science is too complicated for its own good, that interesting and practical results are often best achieved through personal experimentation. Through multiple examples from his own self-experiments, he used his own data to show non-obvious treatments for better sleep (skip breakfast), lower depression (faces in the morning), and many other situations.^[@roberts_self-experimentation_2004]

---

Most of the examples in this book are based on over 600 near-daily samples I took of my own microbiome over a three year period. Inspired by an experiment conducted at MIT^[[@david_host_2014]], during most of that time I also carefully tracked the food I ate, my sleep, and other variables like activity and location. Most of my near-daily samples were of my gut, but I also regularly tested my skin, nose, and mouth. Since I’m generally healthy, I didn’t have a specific goal in mind other than to try to understand better what these microbes are doing, so many of my tests were taken while undergoing simple experiments, like eating a specific type of food or traveling to a new place. While not necessarily up to the rigorous standards of a formal scientific trial, these “n of 1” studies on myself helped me discover several new interesting facts about my own microbiome, many of which appear to contradict other published studies. In addition, hundreds of people sent me their own test results, letting me compare many different microbiomes. And of course, I also followed the latest developments in scientific publications and the general press as I eagerly tried to learn more.

This book tells you what I learned -- and how you can learn too.

---

<!-- 

If you suffer from a chronic condition, one of your first struggles is simply *how bad is it?* What is the precise version or name of this disease? What makes you different from a healthy person, or from the healthy person you used to be? Are there other people with the same condition, and if so, how does your situation compare to theirs? Are you getting better or worse?

In other words, you want to know the *context*. The first step in any treatment plan requires that you understand how you compare…to healthy people, to those who have the same condition as you do, to people who have partially or fully recovered. Are you improving or deteriorating? 

Even symptom tracking is just one aspect of the question of context. I want to know more precisely the conditions under which my problem gets better or worse. In other words, what is the *context*? (e.g. are my migraines triggered by high altitudes, by caffeine, by stress, by something else? All of these are just other ways of saying “context”).

One simple example: what's the best way to treat a headache?  There's no good answer to that question unless you understand something about the context surrounding the person involved. The appropriate response will depend on whether he or she:

* gets headaches all the time.
* rarely gets headaches.
* drank heavily the night before.
* recently ate raw seafood from a street vendor.
* Underwent a course of antibiotics for a tick bite last summer and seemed to get better until now.

We know intuitively that each medical situation depends on the circumstances. Doctors are helpful partly because they've seen so many other cases that they can quickly focus attention on the aspects that are important to a specific individual. In other words, doctors are trained to recognize the full *context*, to see how this situation compares to others.


## Reference Values

Much of our understanding of context is driven by reference values. A doctor knows whether your cholesterol is high or low based on large population studies of other people. Every health study is essentially just a way to calculate reference values: of the n people exposed to this treatment, some fraction will improve. If that fraction is large enough, we say the treatment works. If not, the treatment doesn’t work.

So the real question in any medical condition is: what is the reference value? What is the standard by which I am judging my current condition?

For many (most) situations, the reference values have been pre-computed based the medical community’s long experience treating patients like you. We know that X% of people with your type of cancer respond well to this drug. We know that Y% of people who smoke develop this disease. And on and on.

But for some situations -- like data from microbiome tests -- there is no reference value. Nobody knows what a "healthy" microbiome looks like. We need more data before we can say definitively that such-and-such abundance levels are “healthy” or “unhealthy”.

In other cases, there are reference values for the general population, but not necessarily for you. The average height of a 3-year-old girl, for example, is based on data from umpteen thousands of 3-year-olds, but what about among 3-year-olds of your ethnic group, or your family, or people of your socio-economic class, or those in your neighborhood? Whether to consider *your* 3-year-old for special treatment depends entirely on which reference group you are using.

How can we get those reference values?

In other cases, a treatment may be too new, or too crazy, for there to be reference values. A terminal cancer patient who tries an experimental treatment, for example, is living in a world of unknown reference values. Importantly, after they try the treatment, they become one of the reference values. And that’s great! we now have a reference value for that treatment — but only if somebody bothers to record it. Often that data simply falls on the floor with nobody to catch it.

## Quantifying the anecdotal

If the results of a treatment are not recorded, we still have reference values. People still rely on word of mouth — anecdotes — when looking for new treatments. But those reference values are anecdotal. You regularly hear stories of the form “I tried X and it worked for me”. Hear enough of those stories and you may want to try it yourself. But how many of those stories constitutes “enough” to try for yourself?

What if there were a common way for everyone who tries X to record their results quantitatively?

That’s the idea behind symptom tracking, and it’s a nice start. Some companies try to add fancy additional features on top, like using machine learning to try to guess better than you can alone about the various correlations found within your data. Many companies go this direction — gather enough data, either from yourself or from others, so that we can predict the causes for various states. Again, that’s interesting and it’s a nice start, but it’s limited.

What you really want — and the key, original idea behind Personal Science — is to let you take that quantitative data and *compare* it to others: others like you, people who you consider to be just like you except for such-and-such symptom.

Now, in some cases, a symptom tracking or quantified self product will let you see yourself compared to *an aggregated* summary of all other users. Fitbit might let you compare yourself to all those of your sex or age, for example, or maybe those in your geography. This is a good start.

But what if you could choose your own subset of users with whom you want to compare yourself? Because only *you* know which type of person you identify with, or to which type of health condition you want to belong, Personal Science lets you analyze and study the data as a whole.

That’s why it’s *personal* -- it’s about the one, unique data point that is you -- and why it’s *science* -- democratize the quantitative tools of science to let you understand your condition, for yourself.

-->
