## Akkermansia and me {#experimentAkkermansia}

This is my Akkermansia levels over time.  @fig-AkkermansiaAbundances

```{r}
#| label: fig-AkkermansiaAbundances
#| echo: false
#| message: false
#| fig-cap: "Levels of this key microbe over time"



mhg_taxa_plot(sprague.genus.norm,"Akkermansia")

```


Parkinson's disease is a devastating neurodegenerative disease that affects one in 100 people over age 60, 

Although there is some evidence for a genetic component^[Check out your [LRKK2](https://you.23andme.com/tools/data/?query=LRRK2) status at [23andme](https://you.23andme.com/reports/ghr.parkinsons/)], environment clearly plays a role as well -- which of course, may point to microbes.

[A 2017 review](http://dx.doi.org/10.1016/j.chom.2017.12.008) finds this:

>Since 2015, six studies examining the gut microbiome in Parkinson’s disease (PD) have reported an increase in Akkermansia abundance in PD patients (e.g., Heintz-Buschart et al., 2017; Hill-Burns et al., 2017); indeed, elevated Akkermansia abundance appears to be the most consistently defining feature of the PD microbiome. Likewise, a 2017 study found elevated Akkermansia in individuals with rapid eye movement sleep behavior disorder, which is considered a pre-motor symptom of PD (Heintz-Buschart et al., 2017). 

