### Microbes within you\*

Finally, to round out our overview of how biologists study the microbiome, let's get specific about aspects of our own human bodies, and break it down into components, each of which as we'll see play hosts to unique microbial communities.

But first let's clear up the common misconception that life is a pyramid that goes from "primitive" (bacteria) to "advanced" (humans). While the human body is certainly more complex, with many more moving parts, it's important to remember that humans and our ancestors evolved in a world that was already full of microbes. No bacterium is going to let a new multi-cellular life form emerge without a fight -- or an adaptation -- and the evidence of that struggle is seen in every one of us.

Case in point: we think of our body as consisting of an external "skin" covering an internal set of organs that generally have no access to the outside world. But when multi-cellular life was evolving, why would the bacteria allow such privacy to some of the most important parts of the new bodies? In the constant struggle between existing microbes and newly-emerging multi-cellular life forms, a truce emerged that gave microbes access to the *entire* body, not just the exterior.

We don't normally think about it this way but all multi-cellular life forms, including humans, are shaped like a tube, with the skin on the outside and the gastrointestinal system on the inside. From the mouth to the anus, every creature from fish to mammals is built this way. Furthermore, the inside tube for each of us is airless -- devoid of the oxygen that we think of as essential to life. To our kind of life anyway.

But the interior of a human looks remarkably similar to the world that bacteria would have seen when the very first pre-mammals appeared: low to non-existent amounts of oxygen, no light, steeped in a mucousy salty goo. Think about it that way and you gain more respect for the capabilities of these microbes.

And there are a lot of them. You have 40 trillion bacterial cells in your body -- slightly more than the number of human cells. Combined with the viruses, fungi, and other microscopic DNA-carrying organisms inside you, that's close to 5 million unique genes, compared to only 25,000 human ones. [^microbeswithinyou-1]

[^microbeswithinyou-1]: See the detailed calculations in @sender_revised_2016

When Stanford scientists turned a gene sequencer on DNA fragments found floating in human blood, only about 1% came from previously-identified sources. The rest -- the vast majority -- came from organisms that have never been studied before. [^microbeswithinyou-2]

[^microbeswithinyou-2]: @kowarsky_humans_2017 as described in <https://news.stanford.edu/2017/08/22/nearly-microbes-inside-us-unknown-science/>

Now on to the body itself. The first place to start is with the organ that literally covers us from head to toe.

**Skin**

We usually think of bacteria, fungi, or viruses, as something to eradicate, pests that can only be there to cause problems. The natural state of the body is pristinely washed: clean, with no dirt or other blemishes. This pristine state has never been true. Humans, like all other multi-celled creatures, have lived forever in a bath of foreign ride-hitchers of all types. This micro-fauna is as natural to us as the air we breath, and like air, our bodies *need* a good environment to be at our best.

The body maintains its temperature well, occasionally cooling itself off by channeling excess water through the sweat glands and onto the surface of the skin. Besides water, this sweat contains small amounts of other matter, including elements that toss molecules into the air, many of which, upon landing on the olfactory glands of another person will be sensed as a smell --- also known as body odor.

Nature does not like waste, especially not anything associated with a living body like us, and as soon as those micro elements in sweat are exposed to the air, in the natural state there will be other lifeforms available to devour them, taking out some of the leftover energy in the process of converting them to simpler chemical compounds like carbon dioxide.

One such hanger-on is the bacterium *Nitrosomonas eutropha*[^microbeswithinyou-3]. It thrives in your skin and makes a living from oxidizing, that is, converting to oxygen, the ammonia that is naturally present in the waste secreted by your sweat glands.

[^microbeswithinyou-3]: Unfortunately, the 16S-based testing is not sensitive enough to discriminate this particular genus. To see it in your own samples, you may need to look at the family *Nitrosomonadaceae* or even the order *Nitrosomonadales*

Later we'll discuss what I learned from my own [skin microbiome testing](#experimentSkin).

Healthy skin exhibits a slightly acidic pH (4.2 to 5.6) a level that inhibits pathogenic bacterial colonization but skin pH rises as we age.[^microbeswithinyou-4]

[^microbeswithinyou-4]: see Bowe, Whitney, and Kristin Loberg. 2018. The Beauty of Dirty Skin: The Surprising Science to Looking and Feeling Radiant from the inside Out. First edition. New York: Little, Brown and Company.

*Streptococcus salivarius*, found in the mouth, may combat acne by secreting "bacgeriocinlike inhibitory substance (BLIS).[^microbeswithinyou-5]

[^microbeswithinyou-5]: ibid

Free radical oxidation seems to play a roll in how sometimes the out-of-control microbes result in acne. Applying a topical lotion containing the anti-oxidizing Vitamin E seems to lessen the symptoms, perhaps by suppressing *Bacillus coagulans*.[^microbeswithinyou-6]

[^microbeswithinyou-6]: ibid and <https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4756869/>

New research by Emma Barnard (2017)[^microbeswithinyou-7] on *Propionibacerium acnes* show that acne comes from versions of *P. acnes* that express different (metabolic-related) genes.

[^microbeswithinyou-7]:  <https://www.ncbi.nlm.nih.gov/pubmed/28000755>

Your body is covered in microscopic *Demodex*, a parasitic mite harbored by all humans, but over-represented in people with rosacea (15x). There is evidence that *Demodex* is associated with *P. acnes* [^microbeswithinyou-8]

[^microbeswithinyou-8]: see <https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3296070/>

Your armpits contain glands whose only purpose is to feed bacteria. Applying antiperspirant or deoderant causes significant changes to the ecology of those microbes, and may actually *cause* more odors by increasing numbers of smelly *Actinobacteria*[^microbeswithinyou-9]

[^microbeswithinyou-9]: See @callewaert_deodorants_2014 and <https://www.realclearscience.com/blog/2014/08/antiperspirants_alter_your_armpit_bacteria_and_could_actually_make_you_smell_worse.html>

Skin microbes colonize each pore individually.[^microbeswithinyou-10] The genetic sequence of a microbe strain in one pore can be different than those in another pore. This may be one reason that some skin conditions are so hard to treat. If every pore contains a slightly different colony, there may not be a one-size-fits all way to modify them.

[^microbeswithinyou-10]: See <https://www.sciencedirect.com/science/article/pii/S1931312821005783?via%3Dihub>

**Mouth**

The first stop for any microbe that wants access to your gut, the oral cavity is among the most diverse environments in the body. There's something here for any kind of microbe: low, but fluctutating oxygen levels, generally moist conditions but with plenty of tiny places to hide for those that are water-shy, soft surfaces that rub against the hard enamel of the teeth, all overseen by a tongue that can sweep bits of material from one place to the next.

See what I learned about my mouth microbiome in the chapter on [my oral microbiome](#startMouth).

As with other parts of the body, the microbes here not passive travelers. Many of them perform important functions.

Even your enjoyment of wine appears to be related to the types of microbes in your mouth, according to a 2017 study by Spanish researchers[^microbeswithinyou-11].

[^microbeswithinyou-11]: @belda_microbial_2017

**Nose**

Like the skin, your nose microbiome is permanently exposed to the outside world so it faces different challenges than the mouth or gut, which have some say over when or how they'll come into contact with new microbes. With every breath, your nose microbiome risks exposure to intruders which, once they are inside, may cause major changes to the rest of the microbiome. Unsurprisingly, noses that are regularly exposed to new and different threats will develop more diverse microbiomes.

Dairy farmers, for example, have a wider variety of nasal microbes than do their urban non-farming counterparts. Interestingly, one study shows farmers have lower *Staphylococcus* too, and none of the microbial-resistant kind found in urban dwellers, an indication that the greater competition from all those diverse microbes is actually preventing the emergence of resistance.[^microbeswithinyou-12]

[^microbeswithinyou-12]:  Full study open access here: <http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0183898>

Although the noses of farmers and non-farmers are dominated by the same three phyla, *Firmicutes*, *Actinobacteria*, and *Proteobacteria*, the farmers have much more *Bacteroidetes*, *Tenericutes* and *Verrucomicrobia*.

There is a clear association between the microbiome and smell. Both Alzheimers and Parkinsons researchers have long noted that changes in smell precede symptoms[^microbeswithinyou-13]. Some early AD symptoms, like a loss of smell, may be clues that the brain has been attacked by something that came from outside.

[^microbeswithinyou-13]: Gina Kolata wrote a summary in a [2016 New York Times article](http://www.nytimes.com/2016/05/26/health/alzheimers-disease-infection.html)

The nasal microbiome appears to change during a viral infection, and the overall microbial composition seems to depend on the types of viruses, and whether the person was vaccinated or not.[^microbeswithinyou-14] In a study of 200 New Yorkers, healthy people seemed to have an abundance of *Corynebacterium* and *Streptococcus*, whereas the people with viruses had much lower *Corynebacterium* slightly lower *Streptococcus*, and more *Dolosigranulum*.

[^microbeswithinyou-14]: @ding_microbial_2019. Open access study results here: <https://mbio.asm.org/content/10/4/e01296-19>

Researchers from the University of Graz in Austria published a small study (n=67) @koskinen_nasal_2018[^microbeswithinyou-15] that found clear differences between those with normal sense of smell (n=29) and those without (n=10). In particular, "butyric acid-producing microorganisms were found to be associated with impaired olfactory function".

[^microbeswithinyou-15]: [The nasal microbiome mirrors and potentially shapes olfactory function](https://www.nature.com/articles/s41598-018-19438-3) in Nature Scientific Reports

Some of the microbes most associated with poor ability to smellinclude: *Actinomyces*, *Corynebacterium*, *Bacteroides*, *Anaerococcus*, *Faecalibacterium*, *Pseudomonas*, and others.[^microbeswithinyou-16]

[^microbeswithinyou-16]: Full table here: <https://www.nature.com/articles/s41598-018-19438-3/tables/2>

When [I tested my own nose microbiome](#startNose), I found that the vast majority of microbes are *Corynebacterium* and *Moraxella*, with a steady small amounts of *Dolosigranulum* and *Propionibacterium*. I occasionally have a spike of *Staphylococcus*, a usually benign and perhaps even beneficial microbe that can turn pathogenic under some circumstances.

------------------------------------------------------------------------

Nowhere are the microbes more numerous or obvious than in our guts. The tiny bacteria that come sliding down your insides eventually exit the body entirely, in a pile you've been making anew every day since your birth.

**Stomach**

After chewing, the first big tranformation of your food happens in the stomach, where powerful acids wreak havoc on any microbes that may have come with the food. At a pH of between 1.5 and 3, stomach acid is literally industrial strength: acids of that strength are useful for applications from oil production to household cleaning.

The acidity denatures the proteins in food, making them susceptible to digestive enzymes like pepsin, but what happens to the microbes that came along for the ride?

Not all microbes are destroyed by stomach acid. One in particular, the notorious *Helicobacter Pylori* actually thrives in such environments, by producing urease, an enzyme that neutralizes the area around the microbe.

**The Appendix**

Somewhere near the border between the small intestine and the large intestine (colon), there is a small, pinkie-like appendage bulging inconspicuously into the abdominal cavity. For most of the period of modern western medicine, nobody knew its function other than as a source of severe pain when it occasionally exploded in infections that until the development of antibiotics were usually fatal.

Appendicitis used to be very rare (3-4 cases/year till 1890, up to 113 by 1918), which was fortunate, because there was no treatment. It was a sad fact that, for example the only death among the hundred or so frontiersmen and explorers on the Lewis and Clark expedition in the early 1800s was caused by appendicitis --- a terrible, painful death in the wilderness but one that would have been just as inevitable at the finest hospitals in the world at the time. A Soviet doctor working at a remote base once did a successful appendectomy on himself[^microbeswithinyou-17], but that's not something for most people to try. Even today, appendicitis is so dangerous that a prophylatic appendectomy is a requirement to live in Villas Las Estrellas, a remote research village housing about 100 scientists and crew in Antarctica. [^microbeswithinyou-18]

[^microbeswithinyou-17]: an English translation of the [report from the Soviet doctor](http://www.southpolestation.com/trivia/igy1/appendix.html)

[^microbeswithinyou-18]: see a [BBC photo essay](https://www.bbc.com/future/gallery/20180810-villas-las-estrellas-antarctica-base-residents-surgery)

What's known is that the appendix apparently houses three things: tissue from the immune system, a bunch of what are called IgA antibodies that fight infections, and tons of bacteria. What's also known is that people who have their appendix removed surgically --- usually as a result of one of those terrible infections --- recover to live apparently normal lives, with no side effects even decades upon decades later. So what is the appendix doing?

One clue comes from a 2011 study of 254 patients recovering from a *C. Difficil* infection[^microbeswithinyou-19], a horridly tenacious bacterium that has gained near-complete resistance to antibiotics and is notoriously difficult to treat. In the study, those with an appendix saw their infections come back 11% of the time, but those with no appendix suffered re-infection rates of 44% --- a large and significant difference that has caused most scientists to speculate that the appendix is harboring something that enables the body to recover after a microbial disaster.

[^microbeswithinyou-19]: @im_appendix_2011

Another clue comes from a phylogenetic study of the evolutionary history of 533 mammals[^microbeswithinyou-20]. Some mammals have an appendix and others don't -- it seems to have evolved independently over 30 times -- but interestingly whenever an evolutionary lineage evolves an appendix, it never "devolves". After accounting for all the factors you can think of, from diet to climate, to sociability, the one notable factor among mammals *with* an appendix is that they tend to have higher concentrations of immune tissue in their bowels. Again, this all adds up to the idea that the appendix has something to do with the body's response to microbes.

[^microbeswithinyou-20]: <https://www.sciencedaily.com/releases/2017/01/170109162333.htm>

My own interest in this subject is not idle curiosity. About fifty years ago, doctors at a small town hospital gave an appendectomy to my five-year-old self in order to treat an unusual belly ache. While doing what was apparently an exploratory surgery to find the cause, they came upon my otherwise healthy-looking appendix and decided on the spot to simply remove it. "Why not?" I'm sure they thought at the time. "If nothing else, it'll prevent him from appendicitis", which is as tautologically sound a reason as any.

Did that change me, somehow? Am I fundamentally different because for most of my life I've been missing an important microbe safety zone that the rest of you enjoy? Science doesn't know the answers, and even when there are studies based on well-conducted experiments, I can't know the answer unless I do the experiment on *me*.

Hint: that's exactly what I did as you'll see in [the chapter on my self-experiments](#experiments).

**Small Intestine**

**Colon**

The cells lining the colon, called colonocytes, get much of their energy from butyrate, an acid that has long been known to play a role in digestive health. Named after the Latin word for butter, which contains up to 5% butyrate, its presence in the colon has been linked to lower rates of colitis and colon cancer. Too little butyrate and the colonocytes whither and die.

You can buy butyrate supplements that supposedly help digestion but you can also get it naturally in dairy fats, especially butter, which can be almost 5% butyrate. In fact, both words are derived from the Latin term butyrique

But why eat it directly? Many gut microbes produce it for you, right where it's needed, by fermenting the fiber that makes it to your colon.

Interestingly a low-carb diet doesn't affect levels of *Bacteroidetes* or *Clostridium*, but it can have a substantial impact on *Bifidobacteria*, *Roseburia*, and *Eubacterium Rectale*, all sources of butyrate production.

Butyrate is a one many Short Chain Fatty Acids (SCFA)?

For example, 80% of your serotonin is made in the gut.[^microbeswithinyou-21]

[^microbeswithinyou-21]: "Normal gut microbiota modulates brain development and behavior," Proceedings of the National Academy of Sciences 108 (2011): 3047--52."
