## Alzheimers and the microbiome


"Anne" is a 40-year-old mother with a secret: her 23andme genetic test results show she is homozygous for the APOE-4 variant, which in slightly-misleading-but-you-know-what-I-mean everyday language means she has the gene for Alzheimer’s disease. Statistics show that about 80% of people like her will develop the condition, and with this particular gene variant, it’s likely she may start to see early symptoms as soon as age 50. Scary! No wonder she doesn’t want anyone to know, including her children and relatives.

But Anne is also an optimist: she prefers to see herself as one of the 20% with the gene who *won’t* develop any symptoms. And she’s ready and motivated to do whatever necessary — diet, exercise, lifestyle changes — to beat this thing. She also knows that her body includes much more than human DNA, that for every human gene like that APOE-4 variant, she is host to as many as ten or a hundred times as many microbial genes, including — perhaps — some that with a bit of nurturing might help offset or prevent whatever propensity her human DNA has to this terrible disease.

Scientists researching Alzheimer’s disease have uncovered some intriguing relationships with the microbiome. (see [*this recent New York Times article*](http://www.nytimes.com/2016/05/26/health/alzheimers-disease-infection.html?smprod=nytcore-iphone&smid=nytcore-iphone-share&_r=0) for a summary.) Some early AD symptoms, like a loss of smell, may be clues that the brain has been attacked by something that came from outside. The microbiome of the mouth, especially, is an excellent hiding place for low-grade infectious agents thanks to its many dark corners with regular access to both the inside and outside of the body^[See more here: https://www.semanticscholar.org/paper/The-microbiome-and-disease%3A-reviewing-the-links-the-Shoemark-Allen/89b2295bab63c6d9267dc29198cb829f452efb51?tab=citations ] 
. After reading about these relationships, Anne submitted several oral samples and shared the results with me.

The AD research field has blossomed lately with the realization that the brain, once thought to be completely sterile, is home to many microbes. This discovery and additional research has excited the editors of the respected *Journal of Alzheimers Disease,* who concluded a recent issue^[@itzhaki_microbes_2016 and here:https://content.iospress.com/articles/journal-of-alzheimers-disease/jad160152]:

>We propose that infectious agents, including HSV1, _Chlamydia pneumonia_, and _spirochetes_, reach the CNS (Central Nervous System) and remain there in latent form. These agents can undergo reactivation in the brain during aging, as the immune system declines...The consequent neuronal damage... occurs recurrently, leading to (or acting as a cofactor for) progressive synaptic dysfunction, neuronal loss, and ultimately Alzheimers Disease.

That’s a powerful indictment of specific microbes, and the article calls them out by name. So does Anne have any in her  sample?

Unfortunately, here's where we see both the promise and the limitations of those of us who suspect the microbiome will play an important role in eventually conquering this terrible disease.

The promise is intriguing: if we could identify the specific microbes underlying the condition, and then, perhaps through antibiotics or probiotics or some other intervention, what if we could get rid of the "bad" microbes and reseed with the "good" ones?

Here’s a high-level (phylum) look at Anne’s oral microbiome:

```{r, echo=FALSE}
anne <- subset_samples(people.phylum, Username == "DrMom" & Site =="mouth")
kable(round(mhg_abundance(prune_taxa(taxa_sums(anne)>100, anne))[,1:3]/(10000+runif(1,min=-100,max=100)),2),digits = 2,col.names = c("1","2", "3"))
```

Careful readers will immediately notice the Spirochaetes in those two later samples -- the same microbe identified as a suspect in the *Journal of Alzheimer's Research*. Is this just a coincidence?! Or have we found a link?

At this point, (big groan), we know there are quick-buck charlatans out there who will seize on an observation like this to sell hope to Alzheimer’s sufferers and their families: how about a new anti-Spirochetes supplement? A seven-step “detox” plan to permanently rid your system of Spirochetes? Great idea for a new business, or maybe a best-selling book, right?

Unfortunately there are no shortcuts, and real conclusions from this data are still a ways away.

It turns out that Spirochetes is actually quite common in the oral microbiome. It’s a broad category of free-moving bacteria that like to hide in low-oxygen environments. Its most infamous members include the genus _Troponema_, associated with syphilis, which come to think of it is a disease that affects the brain. (In botany class they like to joke that it’s called Spirochaete because that’s what you get when you cheat).

The Spirochaetes in Anne’s test results are not _Troponema_, but even if they were it wouldn’t mean much. A lot of people have these. I have some in my own mouth microbiome. The ecology of the mouth is so rich and complex that it’s almost never possible to identify something as either “bad” or “good”.  Remember the example from earlier of “viridans” streptococci, the ones that beat back Strep Throat but can also cause heart problems?  

The same is likely to be true about whatever microbes might be involved with Alzheimer's. But the good news is that more sampling can play a role in helping to narrow down the microbes that are different in people who go on to develop the disease. If we can collect enough samples from people like Anne, who have a family history and are at high risk for AD, we can compare them to one another as well as to thousands of samples of people who are normal risk and maybe we’ll see a pattern.

For example, when Anne compared her mouth biome results with those from a close relative, she found that she has these unique phyla. The relative does not have them:

             
|  Anne's Unique Phyla   |   % diff   | 
|-----------------------------|-------| 
| Candidatus Saccharibacteria | 0.08% | 
| Spirochaetes                | 0.01% | 
| Tenericutes                 | 0.00% | 

Interestingly, this relative has none of her Spirochaetes. And we find two others missing as well. Do they matter? Who knows?

The microbiome studies that have been conducted so far on AD patients are too limited to offer suggestions for what Anne can do right now, but slight differences like this offer her some ideas for possible experiments in the meantime.

Anne already follows the general advice that doctors give to everyone, including those at risk of AD, who wants a healthy microbiome: get plenty of exercise and sleep, eat healthy unprocessed foods, and avoid antibiotics. But, just possibly, there are variations on these general good habits that might help her today.

For example, she’s experimenting with different toothpastes to see how that affects her mouth microbiome. Did you know that most of the common toothpaste brands include powerful antibiotics?^[@pischel_triclosan_2014, available here: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5781629/#!po=75.0000 ] Could the difference in brand be responsible for the unique phyla she sees? To learn more about herself, she’s experimenting with alternate brands -- testing her oral microbiome before and after to see the effects.

This is not the end of the story. Sadly we don't know what will ultimately happen to Anne. But through better knowledge of herself, and her microbiome, she's doing everything she can to beat the odds.

